"""
Django settings for mywebsite project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
from .conf.dev import *
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
	ENGINE: '',
	NAME: '',
    }
}

