###
# Clones or pulls the repo from a public or private Git repository
##
- name: ensure Git is installed via the system package
  apt: name=git-core state=present update_cache=yes
  sudo: yes

- name: create deploy key directory if it does not exist
  file: path=/home/{{ deploy_user }}/.ssh state=directory

- name: ensure deploy key is on remote server
  copy: src={{ local_deploy_key_dir }}/id_rsa_ghb_rhs
        dest=/home/{{ deploy_user }}/.ssh/
        mode=0600 owner={{ deploy_user }} group={{ deploy_group }}
- name: Ansible create file with content example
  copy:
    dest: "/home/{{ deploy_user }}/.ssh/config"
    content: |
      Host github.com
        User {{ deploy_user }}
        Hostname github.com
        IdentityFile ~/.ssh/id_rsa_ghb_rhs

- name: clone or pull latest web app code
  git: repo={{ code_repository }} dest={{ app_dir }}
       key_file=/home/{{ deploy_user }}/.ssh/id_rsa_ghb_rhs
       accept_hostkey=yes